server:
  port: 8050

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource: #jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/mydb?characterEncoding=utf-8
    username: root
    password: root1234
    
    
mybatis:
  type-aliases-package: com.wedding.app.vo
  mapper-locations: mapper/*Mapper.xml 
